[package]
name        = "tessera-storage-enterprise"
description = "MVCC, transactions, snapshots and concurrent access for tessera-graph-enterprise"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
rust-version.workspace = true

[dependencies]
tessera-graph  = { workspace = true }
tessera-auth   = { workspace = true }
tessera-config = { workspace = true }
tessera-cypher = { workspace = true }
thiserror      = { workspace = true }
crc32fast      = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
