[package]
name        = "tessera-graph-config"
description = "Configuration management for TesseraGraph"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license-file          = "../tessera-graph-server/LICENSE"
rust-version.workspace = true
publish = false

[dependencies]
thiserror = { workspace = true }

[lints]
workspace = true
