"""Type stubs for tessera_graph — Python bindings for the tessera-graph embeddable graph database."""

from __future__ import annotations
from typing import Any, Callable, Iterator, Optional, Sequence

# ── Exceptions ───────────────────────────────────────────────────────────────

class TesseraError(Exception): ...
class NodeNotFoundError(TesseraError): ...
class EdgeNotFoundError(TesseraError): ...
class GqlSyntaxError(TesseraError): ...

# ── ID types ─────────────────────────────────────────────────────────────────

class NodeId:
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class EdgeId:
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

# ── Graph element types ──────────────────────────────────────────────────────

class Node:
    def id(self) -> NodeId: ...
    def label(self) -> str: ...
    def properties(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Edge:
    def id(self) -> EdgeId: ...
    def label(self) -> str: ...
    def source(self) -> NodeId: ...
    def target(self) -> NodeId: ...
    def properties(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# ── Enums ────────────────────────────────────────────────────────────────────

class Direction:
    OUTGOING: Direction
    INCOMING: Direction
    BOTH: Direction
    @staticmethod
    def from_str(s: str) -> Direction: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Strategy:
    BFS: Strategy
    DFS: Strategy
    @staticmethod
    def from_str(s: str) -> Strategy: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# ── Path ─────────────────────────────────────────────────────────────────────

class Path:
    def nodes(self) -> list[NodeId]: ...
    def edges(self) -> list[EdgeId]: ...
    def start(self) -> Optional[NodeId]: ...
    def end(self) -> Optional[NodeId]: ...
    @property
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[NodeId]: ...
    def __repr__(self) -> str: ...

# ── Subgraph ─────────────────────────────────────────────────────────────────

class Subgraph:
    @property
    def nodes(self) -> list[Node]: ...
    @property
    def edges(self) -> list[Edge]: ...
    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, item: NodeId | Node | EdgeId | Edge) -> bool: ...
    def __repr__(self) -> str: ...

# ── PatternMatch ─────────────────────────────────────────────────────────────

class PatternMatch:
    def get_node(self, var: str) -> Node: ...
    def get_edge(self, var: str) -> Edge: ...
    def __repr__(self) -> str: ...

# ── Query builders ───────────────────────────────────────────────────────────

class NeighborQuery:
    def direction(self, d: Direction | str) -> NeighborQuery: ...
    def label(self, label: str) -> NeighborQuery: ...
    def collect(self) -> list[Edge]: ...
    def node_ids(self) -> list[NodeId]: ...

class TraversalBuilder:
    def direction(self, d: Direction | str) -> TraversalBuilder: ...
    def label(self, label: str) -> TraversalBuilder: ...
    def max_depth(self, depth: int) -> TraversalBuilder: ...
    def bfs(self) -> TraversalBuilder: ...
    def dfs(self) -> TraversalBuilder: ...
    def collect(self) -> list[NodeId]: ...
    def collect_paths(self) -> list[Path]: ...

class ShortestPathQuery:
    def direction(self, d: Direction | str) -> ShortestPathQuery: ...
    def label(self, label: str) -> ShortestPathQuery: ...
    def find(self) -> Optional[Path]: ...

class WeightedPathQuery:
    def direction(self, d: Direction | str) -> WeightedPathQuery: ...
    def label(self, label: str) -> WeightedPathQuery: ...
    def weight(self, weight_fn: Callable[[Edge], float]) -> WeightedPathQuery: ...
    def find(self) -> Optional[tuple[float, Path]]: ...

class SubgraphQuery:
    def direction(self, d: Direction | str) -> SubgraphQuery: ...
    def label(self, label: str) -> SubgraphQuery: ...
    def max_depth(self, depth: int) -> SubgraphQuery: ...
    def extract(self) -> Subgraph: ...

class PatternBuilder:
    def node(self, var: str) -> PatternBuilder: ...
    def edge(self, direction: Direction | str) -> PatternBuilder: ...
    def edge_var(self, var: str, direction: Direction | str) -> PatternBuilder: ...
    def label(self, label: str) -> PatternBuilder: ...
    def where_prop(self, key: str, value: Any) -> PatternBuilder: ...
    def where_edge_prop(self, key: str, value: Any) -> PatternBuilder: ...
    def execute(self) -> list[PatternMatch]: ...

# ── Batch ────────────────────────────────────────────────────────────────────

class BatchContext:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

# ── Graph ────────────────────────────────────────────────────────────────────

class Graph:
    @staticmethod
    def new() -> Graph: ...
    @staticmethod
    def open(
        path: str,
        *,
        create_if_missing: bool = True,
        memory_limit_bytes: int = 67108864,
        wal_enabled: bool = True,
        adj_cache_capacity: int = 65536,
    ) -> Graph: ...
    def flush(self) -> None: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def add_node(self, label: str, properties: dict[str, Any]) -> NodeId: ...
    def node(self, id: NodeId) -> Node: ...
    def node_exists(self, id: NodeId) -> bool: ...
    def node_ids(self) -> list[NodeId]: ...
    def nodes_by_label(self, label: str) -> list[NodeId]: ...
    def remove_node(self, id: NodeId) -> Node: ...
    def update_node(self, id: NodeId, *, label: Optional[str] = None, properties: Optional[dict[str, Any]] = None) -> None: ...
    def add_edge(self, label: str, source: NodeId, target: NodeId, properties: dict[str, Any]) -> EdgeId: ...
    def edge(self, id: EdgeId) -> Edge: ...
    def edges_by_label(self, label: str) -> list[EdgeId]: ...
    def remove_edge(self, id: EdgeId) -> Edge: ...
    def update_edge(self, id: EdgeId, *, label: Optional[str] = None, properties: Optional[dict[str, Any]] = None) -> None: ...
    def outgoing_edges(self, node: NodeId) -> list[Edge]: ...
    def incoming_edges(self, node: NodeId) -> list[Edge]: ...
    def nodes(self) -> list[Node]: ...
    def edges(self) -> list[Edge]: ...
    def neighbors(self, node: NodeId) -> NeighborQuery: ...
    def traverse(self, start: NodeId) -> TraversalBuilder: ...
    def shortest_path(self, source: NodeId, target: NodeId) -> ShortestPathQuery: ...
    def weighted_shortest_path(self, source: NodeId, target: NodeId) -> WeightedPathQuery: ...
    def subgraph(self, start: NodeId) -> SubgraphQuery: ...
    def pattern(self) -> PatternBuilder: ...
    def begin_batch(self) -> None: ...
    def end_batch(self) -> None: ...
    def batch(self) -> BatchContext: ...
    def __repr__(self) -> str: ...

# ── SharedGraph ──────────────────────────────────────────────────────────────

class ReadGuard:
    def __enter__(self) -> ReadGuard: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def node(self, id: NodeId) -> Node: ...
    def node_exists(self, id: NodeId) -> bool: ...
    def node_ids(self) -> list[NodeId]: ...
    def nodes_by_label(self, label: str) -> list[NodeId]: ...
    def edge(self, id: EdgeId) -> Edge: ...
    def edges_by_label(self, label: str) -> list[EdgeId]: ...
    def outgoing_edges(self, node: NodeId) -> list[Edge]: ...
    def incoming_edges(self, node: NodeId) -> list[Edge]: ...

class WriteGuard:
    def __enter__(self) -> WriteGuard: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def node(self, id: NodeId) -> Node: ...
    def node_exists(self, id: NodeId) -> bool: ...
    def node_ids(self) -> list[NodeId]: ...
    def nodes_by_label(self, label: str) -> list[NodeId]: ...
    def edge(self, id: EdgeId) -> Edge: ...
    def edges_by_label(self, label: str) -> list[EdgeId]: ...
    def outgoing_edges(self, node: NodeId) -> list[Edge]: ...
    def incoming_edges(self, node: NodeId) -> list[Edge]: ...
    def add_node(self, label: str, properties: dict[str, Any]) -> NodeId: ...
    def add_edge(self, label: str, source: NodeId, target: NodeId, properties: dict[str, Any]) -> EdgeId: ...
    def remove_node(self, id: NodeId) -> Node: ...
    def remove_edge(self, id: EdgeId) -> Edge: ...
    def update_node(self, id: NodeId, *, label: Optional[str] = None, properties: Optional[dict[str, Any]] = None) -> None: ...
    def update_edge(self, id: EdgeId, *, label: Optional[str] = None, properties: Optional[dict[str, Any]] = None) -> None: ...
    def flush(self) -> None: ...

class SharedGraph:
    @staticmethod
    def new(graph: Graph) -> SharedGraph: ...
    def read(self) -> ReadGuard: ...
    def write(self) -> WriteGuard: ...
    def __repr__(self) -> str: ...

# ── GQL ──────────────────────────────────────────────────────────────────────

class GqlRow:
    def __getitem__(self, key: str) -> Any: ...
    def keys(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class GqlMutationResult:
    @property
    def nodes_created(self) -> int: ...
    @property
    def edges_created(self) -> int: ...
    @property
    def nodes_deleted(self) -> int: ...
    @property
    def edges_deleted(self) -> int: ...
    @property
    def properties_set(self) -> int: ...

class GqlResult:
    @property
    def rows(self) -> list[GqlRow]: ...
    @property
    def mutations(self) -> Optional[GqlMutationResult]: ...
    def __getitem__(self, index: int) -> GqlRow: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[GqlRow]: ...
    def __repr__(self) -> str: ...

def execute(graph: Graph, query: str) -> GqlResult: ...
def validate(query: str) -> bool: ...
