// Copyright 2026 BelowZero Security OU. All rights reserved.

use tessera_graph::{Graph, Property};
use tessera_import::gql_export::export_gql;

fn empty_graph() -> Graph {
    Graph::new()
}

#[test]
fn export_gql_empty_graph_has_header_comment() {
    let g = empty_graph();
    let out = export_gql(&g).unwrap();
    assert!(
        out.contains("// Generated by TesseraGraph Export"),
        "got: {out}"
    );
}

#[test]
fn export_gql_empty_graph_has_edge_limitation_comment() {
    let g = empty_graph();
    let out = export_gql(&g).unwrap();
    assert!(
        out.contains("// NOTE: Edge export is not yet supported."),
        "got: {out}"
    );
}

#[test]
fn export_gql_single_node_create_statement() {
    let mut g = empty_graph();
    let props: tessera_graph::Properties =
        std::iter::once(("name".to_owned(), Property::String("Alice".to_owned()))).collect();
    g.add_node("Person", props).unwrap();
    let out = export_gql(&g).unwrap();
    assert!(out.contains("CREATE (:Person"), "got: {out}");
    assert!(out.contains("name: 'Alice'"), "got: {out}");
}

#[test]
fn export_gql_node_without_props_no_braces() {
    let mut g = empty_graph();
    g.add_node("Empty", tessera_graph::Properties::new())
        .unwrap();
    let out = export_gql(&g).unwrap();
    assert!(out.contains("CREATE (:Empty)"), "got: {out}");
}

#[test]
fn export_gql_integer_property_no_quotes() {
    let mut g = empty_graph();
    let props: tessera_graph::Properties =
        std::iter::once(("age".to_owned(), Property::I64(42))).collect();
    g.add_node("Person", props).unwrap();
    let out = export_gql(&g).unwrap();
    assert!(out.contains("age: 42"), "got: {out}");
}

#[test]
fn export_gql_bool_property_lowercase() {
    let mut g = empty_graph();
    let props: tessera_graph::Properties =
        std::iter::once(("active".to_owned(), Property::Bool(true))).collect();
    g.add_node("User", props).unwrap();
    let out = export_gql(&g).unwrap();
    assert!(out.contains("active: true"), "got: {out}");
}

#[test]
fn export_gql_properties_sorted_alphabetically() {
    let mut g = empty_graph();
    let props: tessera_graph::Properties = [
        ("zzz".to_owned(), Property::I64(1)),
        ("aaa".to_owned(), Property::I64(2)),
    ]
    .into_iter()
    .collect();
    g.add_node("Node", props).unwrap();
    let out = export_gql(&g).unwrap();
    let aaa_pos = out.find("aaa").unwrap();
    let zzz_pos = out.find("zzz").unwrap();
    assert!(aaa_pos < zzz_pos, "props not sorted; got: {out}");
}

#[test]
fn export_gql_string_with_single_quote_escaped() {
    let mut g = empty_graph();
    let props: tessera_graph::Properties =
        std::iter::once(("name".to_owned(), Property::String("O'Brien".to_owned()))).collect();
    g.add_node("Person", props).unwrap();
    let out = export_gql(&g).unwrap();
    // The apostrophe should be escaped as \'
    assert!(out.contains("\\'"), "apostrophe not escaped; got: {out}");
}
