[package]
name        = "tessera-import"
description = "CSV, JSON, and GQL import/export for tessera-graph-enterprise"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
rust-version.workspace = true

[dependencies]
tessera-graph              = { workspace = true }
tessera-storage-enterprise = { workspace = true }
thiserror                  = { workspace = true }
serde                      = { workspace = true }
serde_json                 = { workspace = true }

[lints]
workspace = true
