// Copyright 2026 BelowZero Security OU. All rights reserved.

//! GQL export for `TesseraGraph`.
//!
//! Exports the graph as a sequence of GQL CREATE statements, one per node.
//! Edge export is not yet supported and is documented as a known limitation.

use std::fmt::Write as _;

use tessera_graph::Graph;

use crate::error::ExportResult;
use crate::property_coerce::{property_to_gql_literal, validate_property_key};

/// Export all nodes in the graph as GQL CREATE statements.
///
/// Output format:
/// ```gql
/// // Generated by TesseraGraph Export
/// CREATE (:Person {age: 30, name: 'Alice'})
/// CREATE (:Person {age: 25, name: 'Bob'})
/// // NOTE: Edge export is not yet supported.
/// ```
///
/// Properties are sorted alphabetically for deterministic output.
///
/// # Errors
///
/// Returns [`crate::error::ExportError::GraphRead`] if a node cannot be read.
/// Returns [`crate::error::ExportError::UnsupportedType`] if a property has
/// type `Bytes`.
/// Returns [`crate::error::ExportError::InvalidPropertyKey`] if a property key
/// contains characters outside `[a-zA-Z_][a-zA-Z0-9_]*`.
pub fn export_gql(graph: &Graph) -> ExportResult<String> {
    use crate::error::ExportError;

    let node_count = graph.node_ids().len();
    let mut out = String::with_capacity(50 * (node_count + 1));
    out.push_str("// Generated by TesseraGraph Export\n");

    let mut node_ids = graph.node_ids();
    node_ids.sort_unstable_by_key(|id| id.as_u64());

    for id in node_ids {
        let node = graph
            .node(id)
            .map_err(|e| ExportError::GraphRead(e.to_string()))?;

        let mut sorted_props: Vec<(&String, &tessera_graph::Property)> =
            node.properties().iter().collect();
        sorted_props.sort_by_key(|(k, _)| k.as_str());

        let mut prop_parts: Vec<String> = Vec::with_capacity(sorted_props.len());
        for (k, v) in &sorted_props {
            validate_property_key(k)?;
            let literal = property_to_gql_literal(v)?;
            prop_parts.push(format!("{k}: {literal}"));
        }
        let props_str = prop_parts.join(", ");

        if props_str.is_empty() {
            let _ = writeln!(out, "CREATE (:{label})", label = node.label());
        } else {
            let _ = writeln!(
                out,
                "CREATE (:{label} {{{props}}})",
                label = node.label(),
                props = props_str,
            );
        }
    }

    out.push_str("// NOTE: Edge export is not yet supported.\n");

    Ok(out)
}
