[package]
name        = "tessera-graph-cypher"
description = "Cypher compatibility layer for TesseraGraph"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license-file          = "../tessera-graph-server/LICENSE"
rust-version.workspace = true
publish = false

[dependencies]
tessera-graph  = { workspace = true }
tessera-graph-config = { workspace = true }
moka           = { workspace = true }

[lints]
workspace = true
